package main

// pet.go - bridge to the desktop-pet: bot replies are written to its say-FIFO
// so Onidia speaks them. The FIFO lives at /tmp/desktop-pet-<display>.say
// (the path is logged by the pet at startup). Writes are best-effort and
// never hang the chat: with no pet listening, the open fails with ENXIO and
// we quietly skip.

import (
	"errors"
	"fmt"
	"image"
	"image/png"
	"log"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

// petPipePath derives the say-FIFO path from $DISPLAY exactly the way the
// pet names it (see desktop-pet main.go instanceTag): every '/', ':' and '.'
// becomes '-'. Returns "" when no display is set.
func petPipePath() string {
	disp := os.Getenv("DISPLAY")
	if disp == "" {
		return ""
	}
	tag := strings.Map(func(r rune) rune {
		if r == '/' || r == ':' || r == '.' {
			return '-'
		}
		return r
	}, disp)
	return "/tmp/desktop-pet-" + tag + ".say"
}

// petSay best-effort writes one say-line to the FIFO. The pet parses a
// leading [mood] tag first, then an optional [image <path>] tag whose file it
// decodes into the speech bubble (png/jpeg/gif, see desktop-pet speech.go),
// treating the rest as the caption - so an image reply is forwarded as
// "[mood] [image /tmp/pic.png] answer text". The picture is handed over as
// img (already fetched/generated by chat.go) and encoded to a temp PNG here;
// the pet reads the file the moment it consumes the line.
func petSay(path, mood, text string, img image.Image) {
	if path == "" || (text == "" && img == nil) {
		return
	}

	imgPath := ""
	if img != nil {
		p, err := saveTempPNG(img)
		if err != nil {
			log.Printf("pet: encoding say-image: %v", err)
		} else {
			cleanupSayImages(p) // drop generations the pet has long consumed
			imgPath = p
		}
	}
	line := buildSayLine(mood, text, imgPath)

	// O_NONBLOCK so we get ENXIO instead of blocking forever when the pet
	// is not running (a FIFO write-open waits for a reader otherwise).
	// A short retry covers the pet reopening the pipe between messages.
	var f *os.File
	var err error
	for tries := 0; tries < 3; tries++ {
		f, err = os.OpenFile(path, os.O_WRONLY|syscall.O_NONBLOCK, 0)
		if err == nil {
			break
		}
		if !errors.Is(err, syscall.ENXIO) {
			if imgPath != "" {
				os.Remove(imgPath) // never delivered - do not litter /tmp
			}
			return // no pipe at all -> pet not running, stay quiet
		}
		time.Sleep(50 * time.Millisecond)
	}
	if err != nil {
		if imgPath != "" {
			os.Remove(imgPath)
		}
		return
	}
	defer f.Close()
	if _, err := fmt.Fprintln(f, line); err != nil {
		log.Printf("pet: say write failed: %v", err)
		if imgPath != "" {
			os.Remove(imgPath)
		}
	}
}

// buildSayLine assembles the line the pet expects, in its parse order: mood
// tag, then image tag, then the caption text.
func buildSayLine(mood, text, imgPath string) string {
	line := text
	if imgPath != "" {
		line = "[image " + imgPath + "] " + line
	}
	if mood != "" {
		line = "[" + mood + "] " + line
	}
	return line
}

// sayImagePattern matches the temp PNGs written for pet say-lines.
const sayImagePattern = "chat-app-say-*.png"

// saveTempPNG encodes img as a PNG in a unique temp file and returns its
// path, ready to be referenced from a say-line.
func saveTempPNG(img image.Image) (string, error) {
	f, err := os.CreateTemp("", sayImagePattern)
	if err != nil {
		return "", err
	}
	name := f.Name()
	if err := png.Encode(f, img); err != nil {
		f.Close()
		os.Remove(name)
		return "", err
	}
	if err := f.Close(); err != nil {
		os.Remove(name)
		return "", err
	}
	return name, nil
}

// cleanupSayImages removes temp say-images from earlier replies, keeping
// keep (the file referenced by the newest line - the pet may still be about
// to read it). Keeps /tmp tidy during long chat sessions.
func cleanupSayImages(keep string) {
	matches, err := filepath.Glob(filepath.Join(os.TempDir(), sayImagePattern))
	if err != nil {
		return
	}
	for _, m := range matches {
		if m == keep {
			continue
		}
		os.Remove(m)
	}
}
